#include <stdio.h>
#include <stdlib.h>
int dynamic_memory_allocation_largest() {
    int num;
    float* data;
    printf("Enter the total number of elements: ");
    scanf_s("%d", &num);

    // Allocating memory for num elements
    // 'calloc' allocates the resquested memory and returns a pointer to it. 'calloc' sets allocated memory to zero, 'malloc' does not.
    // (float*) change the address generated by 'calloc' to 'float' type.
    data = (float*)calloc(num, sizeof(float));          // data is actually the address of the allocated memory

    if (data == NULL) {
        printf("Error!!! memory not allocated.");
        exit(0);
    }

    // Storing numbers entered by the user.
    for (int i = 0; i < num; ++i) {
        printf("Enter Number %d: ", i + 1);
        scanf_s("%f", data + i);                // data + i is an address pointer, similar to &variable in 'int' type address
    }

    // Finding the largest number
    for (int i = 1; i < num; ++i) {
        if (*data < *(data + i))                // *data is the value stored at the pointer 'data'
            *data = *(data + i);
    }
    printf("Largest number = %.2f", *data);

    return 0;
}